# library(shiny)
# library(shinyhelper)
# library(data.table)
# library(Matrix)
# library(DT)
# library(magrittr)
# library(ggplot2)
# library(ggrepel)
# library(hdf5r)
# library(ggdendro)
# library(gridExtra)
# library(ggridges)
# library(pkgload)
pkgload::load_all(".")
scRNAseqApp()
